name: KillC
version: '1.0'
main: com.adasjusk.killc.KillC
author: adasjusk
api-version: 1.21
folia-supported: true
description: A plugin that adds kill commands for players with configurable options

commands:
  kill:
    description: Kills yourself or another player. Use "/kill reload" to reload config.
    usage: "/kill [player|reload]"
    permission: killc.use
    permission-message: "You don't have permission to use this command!"
  suicide:
    description: Kills yourself
    usage: "/suicide"
    permission: killc.use
    permission-message: "You don't have permission to use this command!"

permissions:
  killc.use:
    description: Allows using basic kill commands
    default: true
  killc.others:
    description: Allows killing other players
    default: op
  killc.reload:
    description: Allows reloading the plugin configuration
    default: op
  killc.*:
    description: Gives access to all KillC commands
    default: op
    children:
      killc.use: true
      killc.others: true
      killc.reload: true